"""SPEC-CC-parity 记分板清单：契约 → 钉住它的测试。

不是测试文件（不叫 test_*.py，不入套件）。scripts/cc_parity.py 读它、跑列出的
测试、算 parity = 通过数 / 契约总数。`test` 为 None 表示尚未实现或尚未被测试
钉住 —— 两者都不计分：**相信有 ≠ 测出来有**。
"""

CONTRACTS = [
    # id, 组, 契约, 钉住它的测试 id（None = 未钉）
    ("A1", "输入", "Enter 提交，唯一提交键",
     "tests.test_tui_pty.LineEditorTests.test_shift_enter_inserts_newline_and_plain_enter_submits"),
    ("A2", "输入", "换行不提交（Shift/Alt+Enter）",
     "tests.test_tui_pty.PTYTests.test_real_shift_enter_sequences_insert_newlines_without_submit"),
    ("A3", "输入", "多行粘贴是一条 prompt",
     "tests.test_paste_pty.PastePTYTests.test_three_line_paste_becomes_one_prompt_not_three"),
    ("A4", "输入", "Esc 中断当前 turn",
     "tests.test_tui_pty.LineEditorTests.test_escape_cancels_busy_without_mutating_draft"),
    ("A5", "输入", "↑↓ 翻历史",
     "tests.test_tui_pty.InputNavigationTests.test_history_navigation_preserves_draft_and_returns_to_editing"),
    ("A6", "输入", "Ctrl+R 历史搜索",
     "tests.test_history_search_pty.HistorySearchPTYTests.test_ctrl_r_fills_draft_from_history"),
    ("A7", "输入", "@ 文件补全",
     "tests.test_attachments.AttachmentTests.test_line_editor_uses_existing_menu_for_bounded_path_completion"),
    ("A8", "输入", "! 前缀直跑 shell",
     "tests.test_shell_prefix.ShellPrefixTests.test_shell_mode_dispatches_run_shell_not_a_model_turn"),
    ("A9", "输入", "Ctrl+C 清空 / 双按退出",
     "tests.test_ctrl_c.CtrlCTests.test_double_ctrl_c_on_empty_draft_exits"),
    ("B1", "权限", "Shift+Tab 循环权限模式且可见",
     "tests.test_mode_cycle_pty.ModeCyclePTYTests.test_shift_tab_cycles_modes_and_prompt_shows_them"),
    ("B2", "权限", "审批显示最终参数",
     "tests.test_tui_pty.LineEditorTests.test_both_approval_uis_consume_the_prepared_diff_verbatim"),
    ("B3", "权限", "硬边界不在模式循环内",
     "tests.test_bash_guard_bypass.UnsandboxedBranchIsWiredIn.test_read_of_protected_path_is_refused_before_any_process"),
    ("B4", "权限", "plan 模式不落盘",
     "tests.test_goals.GoalCommandTests.test_plan_mode_never_exposes_goal_mutation_tool"),
    ("C1", "渲染", "工具调用一行、结果默认折叠",
     "tests.test_tasks.TaskLifecycleTests.test_artifact_index_maps_call_and_pages_full_result"),
    ("C2", "渲染", "Ctrl+O 展开最近折叠输出",
     "tests.test_ctrl_o_pty.CtrlOPTYTests.test_ctrl_o_expands_folded_thinking_when_no_tool_output"),
    ("C3", "渲染", "spinner：动词+耗时+token",
     "tests.test_tui_pty.RendererTests.test_output_erases_visible_spinner"),
    ("C4", "渲染", "长输出不刷屏",
     "tests.test_long_output_fold.LongOutputFoldTests.test_two_thousand_lines_fold_to_one_line_with_expand_hint"),
    ("C5", "渲染", "todo 原地更新",
     "tests.test_plans.PlanTests.test_todo_tool_emits_structured_runtime_event"),
    ("C6", "渲染", "结构化前缀对齐",
     "tests.test_structural_prefix.StructuralPrefixTests.test_hydrated_transcript_puts_one_space_between_icon_and_heading"),
    ("D1", "思考", "思考过程折叠显示",
     "tests.test_thinking_pty.ThinkingPTYTests.test_reasoning_events_are_folded_and_expandable"),
    ("D2", "思考", "首字延迟分阶段解释",
     "tests.test_latency_pty.LatencyPTYTests.test_status_line_explains_the_wait_before_first_token"),
    ("D3", "思考", "失败三分文案",
     "tests.test_failure_triage.FailureTriageTests.test_the_three_failures_read_differently"),
    ("E1", "会话", "--resume 选择器 / --continue",
     "tests.test_session_picker_pty.SessionPickerPTYTests.test_resume_picker_full_workflow_preserves_state_and_main_draft"),
    ("E2", "会话", "恢复后重投影时间线",
     "tests.test_resume_reprojection.ResumeReprojectionTests.test_resume_paints_each_message_once_in_order"),
    ("E3", "会话", "自动 compact 且有提示",
     "tests.test_context_projection.BudgetAndExplainability.test_compaction_boundary_keeps_whole_user_tool_turns"),
    ("E4", "会话", "状态栏：模型/上下文/成本",
     "tests.test_sandbox_integration.SandboxVisibilityTests.test_footer_keeps_sandbox_marker_next_to_chat_attributes"),
    ("F1", "后台", "Ctrl+B 转后台",
     "tests.test_tui_tasks.CtrlBKeyTests.test_read_key_decodes_ctrl_b"),
    ("F2", "后台", "后台任务一处可见",
     "tests.test_task_cli.TaskCommandTests.test_tasks_lists_mode_status_elapsed_and_output"),
    ("F3", "后台", "工作中可排队",
     "tests.test_tui_pty.LineEditorTests.test_busy_tab_queues_next_turn_and_up_retrieves"),
    ("F4", "后台", "工作中的斜杠命令",
     "tests.test_busy_menu_pty.BusyMenuPTYTests.test_slash_opens_the_live_menu_during_streaming"),
    ("G1", "命令", "/ 面板模糊过滤",
     "tests.test_tui_pty.LineEditorTests.test_command_menu_completion_remains_idle_only"),
    ("G2", "命令", "? 快捷键总览",
     "tests.test_keys_overlay.KeysOverlayTests.test_question_mark_opens_overlay_without_calling_the_model"),
    ("G3", "命令", "稳定按键词汇 ≤ 10",
     "tests.test_keys_overlay.KeysOverlayTests.test_stable_chord_vocabulary_is_at_most_ten"),
    ("H1", "通知", "完成响铃",
     "tests.test_notify_pty.NotifyPTYTests.test_bell_rings_once_after_the_turn"),
    ("H2", "通知", "终端标题随状态",
     "tests.test_notify_pty.NotifyPTYTests.test_title_tracks_state_and_is_cleared_on_exit"),
    ("H3", "通知", "退出时终端干净",
     "tests.test_bracketed_paste.TerminalModeTests.test_nesting_keeps_paste_on_until_the_outermost_exit"),
    # J 组：后台工作的可见性（PLAN-agent-visibility-20260907）
    ("J1", "可见性", "子代理完成落永久行（label · 动词 · 耗时 · token）",
     "tests.test_agent_visibility_pty.AgentVisibilityPTYTests.test_finished_lines_waiting_line_roster_and_status_count"),
    ("J2", "可见性", "子代理正文不进父时间线",
     "tests.test_agent_visibility_pty.AgentVisibilityPTYTests.test_finished_lines_waiting_line_roster_and_status_count"),
    ("J3", "可见性", "等待行原地替换、带剩余个数",
     "tests.test_agent_visibility_pty.AgentVisibilityPTYTests.test_finished_lines_waiting_line_roster_and_status_count"),
    ("J4", "可见性", "名册随活代理出现/消失，行含席位·label·activity·耗时·token",
     "tests.test_agent_visibility_pty.AgentVisibilityPTYTests.test_finished_lines_waiting_line_roster_and_status_count"),
    ("J5", "可见性", "状态栏 N agents",
     "tests.test_agent_visibility_pty.AgentVisibilityPTYTests.test_finished_lines_waiting_line_roster_and_status_count"),
    ("J6", "可见性", "通知体标明非用户输入、带用量、与界面行同源",
     "tests.test_agent_events.NotificationTests.test_notification_is_marked_and_shares_facts_with_the_timeline_line"),
    ("J7", "可见性", "subagent / workflow 节点 / Ctrl+B task 同一套行",
     "tests.test_agent_events.ConvertersTests.test_task_event_and_workflow_node_share_the_shape"),
]
